#version: '2'
#
#services:
#  app:
#    container_name: ipolyclinic
#    image: 'docker-spring-boot-postgres:latest'
#    build:
#      context: .
#    depends_on:
#      - db
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/edu
#      - SPRING_DATASOURCE_USERNAME=postgres
#      - SPRING_DATASOURCE_PASSWORD=-postgres
#      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
#
#  db:
#    container_name: postgres
#    image: 'postgres:13.1-alpine'
#    restart: always
#    ports:
#      - 5432:5432
#    environment:
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
#      - POSTGRES_DB=edu

version: '3'

services:
  db:
    container_name: postgres
    image: postgres
    build:
      context: .
      dockerfile: db.Dockerfile
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
#      - ./var/pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always
    ports:
      - "5430:5432"
    environment:
      PGDATA: /var/lib/postgresql/data
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
#      POSTGRES_DB: polyclinic

  app:
    container_name: ipolyclinic
    image: docker-spring-boot-postgres:latest
    build:
      context: .
#      context: ./docker
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8088:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/polyclinic
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: polyclinic

